include(CheckSymbolExists)
check_symbol_exists(le16toh endian.h HAVE_DECL_LE16TOH)
check_symbol_exists(le32toh endian.h HAVE_DECL_LE32TOH)
check_symbol_exists(le64toh endian.h HAVE_DECL_LE64TOH)
check_symbol_exists(htole16 endian.h HAVE_DECL_HTOLE16)
check_symbol_exists(htole32 endian.h HAVE_DECL_HTOLE32)
check_symbol_exists(htole64 endian.h HAVE_DECL_HTOLE64)
check_symbol_exists(be16toh endian.h HAVE_DECL_BE16TOH)
check_symbol_exists(be32toh endian.h HAVE_DECL_BE32TOH)
check_symbol_exists(be64toh endian.h HAVE_DECL_BE64TOH)
check_symbol_exists(htobe16 endian.h HAVE_DECL_HTOBE16)
check_symbol_exists(htobe32 endian.h HAVE_DECL_HTOBE32)
check_symbol_exists(htobe64 endian.h HAVE_DECL_HTOBE64)
if (HAVE_DECL_LE16TOH AND HAVE_DECL_LE32TOH AND HAVE_DECL_LE64TOH AND HAVE_DECL_HTOLE16 AND HAVE_DECL_HTOLE32 AND HAVE_DECL_HTOLE64 AND
    HAVE_DECL_BE16TOH AND HAVE_DECL_BE32TOH AND HAVE_DECL_BE64TOH AND HAVE_DECL_HTOBE16 AND HAVE_DECL_HTOBE32 AND HAVE_DECL_HTOBE64)
    add_compile_definitions(HAVE_ENDIAN_H)
elseif(HAVE_DECL_LE16TOH AND HAVE_DECL_LE32TOH AND HAVE_DECL_LE64TOH AND HAVE_DECL_HTOLE16 AND HAVE_DECL_HTOLE32 AND HAVE_DECL_HTOLE64 AND
    HAVE_DECL_BE16TOH AND HAVE_DECL_BE32TOH AND HAVE_DECL_BE64TOH AND HAVE_DECL_HTOBE16 AND HAVE_DECL_HTOBE32 AND HAVE_DECL_HTOBE64)
    check_symbol_exists(le16toh sys/endian.h HAVE_DECL_LE16TOHSYS)
    check_symbol_exists(le32toh sys/endian.h HAVE_DECL_LE32TOHSYS)
    check_symbol_exists(le64toh sys/endian.h HAVE_DECL_LE64TOHSYS)
    check_symbol_exists(htole16 sys/endian.h HAVE_DECL_HTOLE16SYS)
    check_symbol_exists(htole32 sys/endian.h HAVE_DECL_HTOLE32SYS)
    check_symbol_exists(htole64 sys/endian.h HAVE_DECL_HTOLE64SYS)
    check_symbol_exists(be16toh sys/endian.h HAVE_DECL_BE16TOHSYS)
    check_symbol_exists(be32toh sys/endian.h HAVE_DECL_BE32TOHSYS)
    check_symbol_exists(be64toh sys/endian.h HAVE_DECL_BE64TOHSYS)
    check_symbol_exists(htobe16 sys/endian.h HAVE_DECL_HTOBE16SYS)
    check_symbol_exists(htobe32 sys/endian.h HAVE_DECL_HTOBE32SYS)
    check_symbol_exists(htobe64 sys/endian.h HAVE_DECL_HTOBE64SYS)
    if(HAVE_DECL_LE16TOHSYS AND HAVE_DECL_LE32TOHSYS AND HAVE_DECL_LE64TOHSYS AND HAVE_DECL_HTOLE16SYS AND HAVE_DECL_HTOLE32SYS AND HAVE_DECL_HTOLE64SYS AND
        HAVE_DECL_BE16TOHSYS AND HAVE_DECL_BE32TOHSYS AND HAVE_DECL_BE64TOHSYS AND HAVE_DECL_HTOBE16SYS AND HAVE_DECL_HTOBE32SYS AND HAVE_DECL_HTOBE64SYS)
        add_compile_definitions(HAVE_SYS_ENDIAN_H)
    endif()
endif()
